### ISSUE TITLE
/etc/hosts is not updated on vdestroy

### ISSUE THREAD

**Issue by scollier** [purpleidea/oh-my-vagrant#100]
When running vdestroy on a node, omv states that it is updating the file on active guest machines.

```
$ vdestroy node1
Unlocking shell provisioning for: node1...
Running 'subscription-manager unregister' on: node1...
Connection to 192.168.121.72 closed.
System has been unregistered.
==> node1: Removing domain...
==> node1: Updating /etc/hosts file on active guest machines...
```

However, when I log into an active machine and check `/etc/hosts` the entry is still there:

```
$ vssh master2

[vagrant@master2 ~]$ sudo -i

[root@master2 ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

## vagrant-hostmanager-start
192.168.123.100	master1.example.com	master1
192.168.123.101	master2.example.com	master2
192.168.123.102	master3.example.com	master3
192.168.123.103	node1.example.com	node1
192.168.123.3	omv.example.com	omv
```

Should omv / the hostmanager plugin actually be updating?  My version of vagrant on the host:

```
$ rpm -qa vagrant
vagrant-1.7.2-7.fc21.1.noarch
```

**Comment by purpleidea** [comment]
@scollier the hostmanager plugin will ensure the /etc/hosts files matches the vagrant reality of defined machines, IOW what you see when you run `vagrant status`. This means even if a machine is "destroyed", it's still defined. You define machines in omv by setting the vms variable and/or count variable in `omv.yaml`. If you don't want a machine to appear in /etc/hosts remove it from the omv.yaml definition.

Please note, when you change this, the vms will be renumbered if you haven't statically set IP addresses.
So if you remove master 2, master3 will get the ip 192.168.123.102.

Lastly, please explain the *problem* you are having that entries in /etc/hosts are causing you :)

**Comment by scollier** [comment]
The problem is that the message states that `==> node1: Updating /etc/hosts file on active guest machines...` it is cleaning up the environment.  It's not causing any immediate issues, but it's certainly not adding anything useful.  I'd rather not have entries in my hosts file that don't exist.

Now, if the host file is configured per defined machines, then that's one thing.  However, the message says `active` guest machines.  It doesn't say `defined` machines.

**Comment by purpleidea** [comment]
@scollier I understand your point, however those are things/design choices (even if they are bugs) that vagrant defined, not oh-my-vagrant. OMV just wraps whatever vagrant does to make that part easier. I'd love to offer you a better solution, but for the moment, I have no ideas.

Either send a patch here or upstream if you think of something, and open a new ticket if there's a fix I didn't think of.

Cheers!
