### ISSUE TITLE
omv --version reports version of Vagrant and not of omv itself

### ISSUE THREAD

**Issue by goern** [purpleidea/oh-my-vagrant#102]
`omv --version` is reporting the version of Vagrant and not of omv, it should report omv's version

```
$ omv --version
Vagrant 1.7.2
```

**Comment by purpleidea** [comment]
Added in
https://github.com/purpleidea/oh-my-vagrant/commit/ddae42d2493261581757d8451fe1a604becd852e

Version 0.0.24
