### ISSUE TITLE
Not parseable Vagrantfile in 0.0.31

### ISSUE THREAD

**Issue by miminar** [purpleidea/oh-my-vagrant#111]
I've just installed oh-my-vagrant-0.0.31-1.noarch from COPR on F21. Running `omv init` in a clean directory gives me:

    There is a syntax error in the following Vagrantfile. The syntax error
    message is reproduced below for convenience:

    /usr/share/oh-my-vagrant/vagrant/Vagrantfile:1520: syntax error, unexpected end-of-input, expecting keyword_end

Downgrading to oh-my-vagrant-0.0.30-1.noarch helped.

**Comment by purpleidea** [comment]
@miminar This was a bug that snuck in after the Nth review of a patch got merged without being more thorough. Please excuse our apologies, and know that it is fixed in later versions. 0.0.33 is the most current, and fixes this bug and one more minor bug too.

Cheers,
James

**Comment by miminar** [comment]
Thanks James. Fedora 21's copr repository seems like it's slacking behind though. Once anything newer gets in there, I'll give it a try.

**Comment by purpleidea** [comment]
On Tue, Aug 18, 2015 at 2:16 AM, Michal Minar <notifications@github.com>
wrote:

> Thanks James. Fedora 21's copr repository seems like it's slacking behind
> though. Once anything newer gets in there, I'll give it a try.



yum clean all
and then
yum update oh-my-vagrant


You should see it :) The copr build status says it should be there!

**Comment by miminar** [comment]
Yep, you're right :-).

**Comment by purpleidea** [comment]
On Tue, Aug 18, 2015 at 3:14 AM, Michal Minar <notifications@github.com>
wrote:

> Yep, you're right :-).



Feel like sending an FAQ patch about this issue?
dnf commands are:

sudo dnf clean metadata --disablerepo=*
--enablerepo=purpleidea-oh-my-vagrant
sudo dnf update oh-my-vagrant

Cheers,
James
