### ISSUE TITLE
How to define shell script in `omv.yaml`

### ISSUE THREAD

**Issue by pschiffe** [purpleidea/oh-my-vagrant#127]
I have in `omv.yaml`:
```
:shell:
- :script: echo hi > /home/vagrant/hello
```

But it doesn't get executed, without any info in vagrant.log. Am I doing something wrong? Using oh-my-vagrant rpm 1.0.1.

**Comment by purpleidea** [comment]
Copy and paste from the example:

https://github.com/purpleidea/oh-my-vagrant/blob/master/examples/shell.yaml

The issue is you used the :shell variable instead of shell (no leading colon)

**Comment by purpleidea** [comment]
Sorry I mean script

**Comment by purpleidea** [comment]
Copy and paste from the example:

https://github.com/purpleidea/oh-my-vagrant/blob/master/examples/shell.yaml

The issue is you used the :script variable instead of script (no leading colon)

**Comment by pschiffe** [comment]
Thank you.
