### ISSUE TITLE
Fedora naming schema lead to unidentified atomic host

### ISSUE THREAD

**Issue by goern** [purpleidea/oh-my-vagrant#139]
OMV is using `is_atomic = vm.vm.box.start_with? 'atomic-'` to identift if a host is an Atomic Host, but Fedora names their boxes something like `fedora/23-atomic-host` or `fedora/23-cloud-base` so OMV will not identify the Atomic Host.

**Comment by purpleidea** [comment]
They should not name their boxes something stupid, but more importantly, the name is what *you* give it. So when you add a box, simple name it atomic-whatever and it will work.

If you'd like to add a patch to download them automatically, please do :)
