### ISSUE TITLE
RFE: have the shell provisioner be extendable

### ISSUE THREAD

**Issue by goern** [purpleidea/oh-my-vagrant#3]
I would like to have a extendable shell provision going on on vagrant up|provision, so that (beside) the shell provision steps inside of the Vagrantfile additionally (user provided) shell scripts get executed. So it may be a good idea to have a provision.d/ within the vagrant/ directory.

Thanks James, Christoph

**Comment by purpleidea** [comment]
Now possible (examples attached) in https://github.com/purpleidea/oh-my-vagrant/commit/cec25b9a9c17a81956cc6457706bab0b358a9708

Docs definitely need some love. Patches and testing appreciated.
