### ISSUE TITLE
ansible support might have some issues and needs proper testing

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/oh-my-vagrant#72]
The ansible support that was added was only mildly tested and needs some more love. This is a reminder issue that it may not be bomb proof yet. If someone confirms that it is, we can happily close this.

**Comment by br0ziliy** [comment]
Just to let you know I'm working on "omv-ansible-pulp", full blown set of Ansible roles and omv.yaml config. The goal is to quickly provision a "clustered" pulp environment using just a couple of git commands and single "vagrant up" command.
You might see some pull requests here.

**Comment by purpleidea** [comment]
@br0ziliy Sounds good! I'm going to close this issue since it looks like you're hacking on ansible things and will find any problems.

New patches/issues accepted!
