### ISSUE TITLE
We should provide an option to update the machine

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/oh-my-vagrant#75]
Some users might not have a completely up to date base box.
They might also want to ensure they have the latest packages if they are hacking on something that changes very often (eg: kubernetes).
Since we live in the dark ages of good internet, it might be nice to offer to update the vagrant box on first up, instead of requiring the user to do this manually, since it might be faster than re-downloading or building a new base image.

This should be a config option named 'update' or similar. It would be true/false, with a default to false.
It should only run on first up, and so should be in the "only one once" part of the Vagrantfile, eg: here:
https://github.com/purpleidea/oh-my-vagrant/blob/master/vagrant/Vagrantfile#L764 (i think).

It should run the yum update command with the shell provisioner...

Cheers,
James

PS: Bonus points for a future version of the patch:
Once we can detect atomic (not merged yet) then do an atomic update instead...

**Comment by purpleidea** [comment]
Good news everyone! @scollier has volunteered to give his hand at this patch!

**Comment by purpleidea** [comment]
Remember to update the examples/ files to add that variable in too.

If you want to add docs patches, those are welcome, but I won't block without them.

**Comment by purpleidea** [comment]
The update variable should probably sit in the boiler plate just underneath the count variable:
https://github.com/purpleidea/oh-my-vagrant/blob/master/vagrant/Vagrantfile#L81

If you need any other guidance, lmk.

**Comment by purpleidea** [comment]
For the atomic use case, I think we should probably run:

```
atomic host upgrade -r
```

Or something similar instead.

**Comment by purpleidea** [comment]
Part of this is merged in: https://github.com/purpleidea/oh-my-vagrant/commit/f776a697ccad9ec91f4463694150cace0434f18a

I'll leave this open for the atomic part.

**Comment by purpleidea** [comment]
Whoa how did github know to auto close this??

**Comment by pschiffe** [comment]
@purpleidea https://help.github.com/articles/closing-issues-via-commit-messages/
