### ISSUE TITLE
Documentation could use some love.

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/oh-my-vagrant#79]
If you're willing to help out and submit some DOCUMENTATION ( https://github.com/purpleidea/oh-my-vagrant/blob/master/DOCUMENTATION.md ) updates, that would be appreciated!

Thanks!

**Comment by ncoghlan** [comment]
Submitted PR #94 to try to give a better up front answer to "How can OMV help me?" for folks that aren't already familiar with Vagrant.

**Comment by purpleidea** [comment]
@ncoghlan sweet. Merged, thanks!

I want to leave this bug continually open in case anyone wants to send us more love!

**Comment by purpleidea** [comment]
Props to @br0ziliy who just got a bunch of patches merged!

**Comment by purpleidea** [comment]
I'm closing this, since docs are in pretty good shape. Doc improvements, patches, etc continually welcome!
