### ISSUE TITLE
repos will be applied to atomic hosts, and fail

### ISSUE THREAD

**Issue by goern** [purpleidea/oh-my-vagrant#83]
using the repos var will result in failures on atomic host, there is no yum repo management on atomic hosts.

**Comment by purpleidea** [comment]
... So don't use it on atomic :P 

Is there a bug we should fix?

**Comment by goern** [comment]
ja, s-m repo management must not be applied to atomic hosts. can I configure that today? if not, this issue is a RFE

**Comment by purpleidea** [comment]
Just don't specify any values in the repos variable.

**Comment by goern** [comment]
erm, ok, ja :) :100:
