### ISSUE TITLE
[RFE] Ability to configure various libvirt VM parameters

### ISSUE THREAD

**Issue by br0ziliy** [purpleidea/oh-my-vagrant#92]
I miss the below functionality in OMV:

- ability to adjust number of CPUs/set RAM size for a VM
- ability to assign additional HDD(s) to a VM

I saw some code blocks related to the HDDs, and also don't see any issues about adding RAM/CPU parameters to the omv.yaml and have Vagrantfile modified accordingly.
Does it worth looking at, or there're some strong reasons why it's still not implemented?
If the only reason is lack of time - I can try to come up with a patch.

**Comment by purpleidea** [comment]
Patches definitely welcome.

As for RAM/CPU's, @goern started this patch in: https://github.com/purpleidea/oh-my-vagrant/pull/84 but then gave up. Please feel free to write it from scratch or fix his. It should be straightforward.

As for additional HDD's, I actually wrote this feature in vagrant-libvirt, so I'm happy to get it in OMV :) You can look at this: https://github.com/purpleidea/puppet-gluster/blob/master/vagrant/Vagrantfile#L483 for how to add disks, assuming the interface hasn't changed.

HTH,
James

**Comment by purpleidea** [comment]
PS: technically OMV works with virtualbox now too. So bonus points if your patch adds the virtualbox hooks, although I won't nack the patch if you don't have them.

**Comment by br0ziliy** [comment]
TBH I did not use VirtualBox for like 7 years now and have no idea how stuff works there this days. Though this does not look like a bad idea to make RAM/CPU/HDD adjustments unified, I will poke around in that direction.

Patch in #84 looks reasonable (well, https://github.com/goern/oh-my-vagrant/commit/f2186d5ae67d18e171a9dfbbe9ba39558521da75 at least), so I'll use it as a basis for my work, thanks James for pointing that out.

**Comment by purpleidea** [comment]
On Fri, May 29, 2015 at 12:27 PM, br0ziliy <notifications@github.com> wrote:

> TBH I did not use VirtualBox for like 7 years now and have no idea how
> stuff works there this days. Though this does not look like a bad idea to
> make RAM/CPU/HDD adjustments unified, I will poke around in that direction.



I don't use virtualbox either. Libvirt works so much better! Feel free to
ignore those additions. We'll open an issue for that feature and have a
virtualbox user add that in later.

**Comment by purpleidea** [comment]
@br0ziliy ping, still planning on doing this?

Cheers!

**Comment by br0ziliy** [comment]
Hey James,

Yes, sure - was just a bit busy during RH Summit times. I'm definitively on
it though - it's just the time that is the matter.

On Thu, Jul 2, 2015 at 12:54 PM, James <notifications@github.com> wrote:

> @br0ziliy <https://github.com/br0ziliy> ping, still planning on doing
> this?
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/purpleidea/oh-my-vagrant/issues/92#issuecomment-117996866>
> .
>



-- 
Vasiliy Kaygorodov
System Administrator

**Comment by purpleidea** [comment]
@br0ziliy @goern 

Just added: https://github.com/purpleidea/oh-my-vagrant/commit/92dd418cedd5f86b9ff9851dfbca9a5e7763a29b

This should meet everything but the disk configuration aspect. I'll close this ticket for now, until someone actually wants to submit a patch for the disk part.

Please test and confirm this works! I've also tagged this release as 0.0.16 and a COPR build exists too:
https://copr.fedoraproject.org/coprs/purpleidea/oh-my-vagrant/

Cheers!

**Comment by purpleidea** [comment]
cc @aweiteka @scollier 
Please test... ^^^^

@flavio-fernandes 
Can you confirm this works on virtualbox.

Thanks!

**Comment by br0ziliy** [comment]
@purpleidea Thanks for implementing this - works like a charm (tested with vagrant-libvirt)

**Comment by purpleidea** [comment]
@br0ziliy YW! enjoy
