### ISSUE TITLE
[RFE] implement update feature for atomic hosts

### ISSUE THREAD

**Issue by goern** [purpleidea/oh-my-vagrant#93]
`update: true` will result in a `yum update` inside the box, this is pretty nice, if you run RHEL/CentOS/Fedora Server, if is useless on Atomic Hosts.

implement `update` so that an Atomic Host is identified and a `atomic host upgrade` is called.

**Comment by purpleidea** [comment]
duplicate of https://github.com/purpleidea/oh-my-vagrant/issues/75

**Comment by goern** [comment]
this is not is duplicate but a refinement to track an individual feature of #75 more easily
