### ISSUE TITLE
We should support a mainstream ("installable") mode

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/oh-my-vagrant#96]
Similar to what @rbarlow proposed in https://github.com/purpleidea/oh-my-vagrant/pull/89

**Comment by purpleidea** [comment]
So I think this is a fairly good idea, particularly for people who want this packaged.

Here's a feature branch:

https://github.com/purpleidea/oh-my-vagrant/tree/feat/installable

Comments appreciated!

**Comment by goern** [comment]
+1 could you elaborate a little on 'how does it feel'? The user will install a .rpm and than call some `omv init` to get ... or just put an omv.yaml anywhere and call `omv up` ?

**Comment by purpleidea** [comment]
On Thu, Jul 2, 2015 at 4:04 AM, Christoph Görn <notifications@github.com>
wrote:

> +1 could you elaborate a little on 'how does it feel'? The user will
> install a .rpm and than call some omv init to get ... or just put an
> omv.yaml anywhere and call omv up ?
>


Correct!
omv foo does exactly what vagrant foo does, except it only needs omv.yaml.

**Comment by purpleidea** [comment]
Merged to git master as https://github.com/purpleidea/oh-my-vagrant/commit/aa764ae79d69475b87f293c43af4f20fd7d1d000

**Comment by rbarlow** [comment]
Niiiiice!
