### ISSUE TITLE
Do not try to unsubscribe uninitialized machines

### ISSUE THREAD

**Issue by scollier** [purpleidea/oh-my-vagrant#97]
When running a `vdestroy`, omv tries to unsubscribe machines that have never been initialized.  Perhaps omv should check the status of the machine before trying to unsubscribe it.  To reproduce the issue: 

Example:

```
$ vs
Current machine states:

master1                   running (libvirt)
master2                   running (libvirt)
master3                   running (libvirt)
node1                     not created (libvirt)


$ vdestroy node1
Running 'subscription-manager unregister' on: node1...
==> node1: Domain is not created. Please run `vagrant up` first.
==> node1: Remove stale volume...
==> node1: Domain is not created. Please run `vagrant up` first.
```

**Comment by purpleidea** [comment]
@scollier vagrant (and omv) runs the command you ask it to. We can actually detect in omv which command vagrant is running eg: https://github.com/purpleidea/oh-my-vagrant/blob/master/vagrant/Vagrantfile#L552 but at the moment, without recursively calling vagrant status (a bad idea) I don't know how to get the status of a particular machine during a vagrant run.

If this is possible, LMK and we can patch OMV. Until this, it's not.
So I'll leave this open for a week if you want to ask around... Maybe on the mitchellh/vagrant project?

**Comment by purpleidea** [comment]
No updates. Please open a new issue upstream or here if you still have this problem.
