### ISSUE TITLE
puppet repos by default

### ISSUE THREAD

**Issue by scollier** [purpleidea/oh-my-vagrant#98]
In my omv.yaml file, I have, which is set by default:

```
:puppet: false
```

omv is still installing these repos:

```
puppetlabs-deps                                                                                                                                       | 2.5 kB  00:00:00     
puppetlabs-products                                                                                                                                   | 2.5 kB  00:00:00     
```

I'd prefer that no puppet repos were added by default when the flag is set to `false`.

**Comment by purpleidea** [comment]
No it's not. Those puppetlabs repos are most likely part of a base image you downloaded. The base images produced with https://github.com/purpleidea/vagrant-builder that I host at https://dl.fedoraproject.org/pub/alt/purpleidea/vagrant do indeed have puppet. We can consider removing that in the default images and/or you can roll your own base images.
