### ISSUE TITLE
/etc/hosts entry for omv

### ISSUE THREAD

**Issue by scollier** [purpleidea/oh-my-vagrant#99]
In my omv file, I disabled any omv VMs from being created:

```
:namespace: omv
:count: 0
```

However, when I take a look at the `/etc/hosts`/ file on a VM, I see:

```
$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

## vagrant-hostmanager-start
192.168.123.100	master1.example.com	master1
192.168.123.101	master2.example.com	master2
192.168.123.102	master3.example.com	master3
192.168.123.103	node1.example.com	node1
192.168.123.3	omv.example.com	omv
```

Which includes an entry for `omv.example.com`.  Any way to disable that?

**Comment by purpleidea** [comment]
Firstly, why do you *want* to disable that?
Secondly, the entries are there on a machine from a previous run. If you want to update the /etc/hosts entries to reflect the current reality, run: vp <name>
eg: vagrant provision somehostname

Lastly, the omv.example.com is a special entry reserved for virtual ip's and things like that. It shouldn't get in your way. If it's a problem, please explain why.

**Comment by scollier** [comment]
I would prefer not to have anything that I didn't intentionally add. Especially when I explicitly say `count 0` in the config file.  It might not get in the way, but what does it add?  Can you explain what the virtual IP is getting me?

**Comment by purpleidea** [comment]
@scollier it's useful for some projects to be able to have a single additional hostname/ip available/reserved on all machines. A number of distributed clusters find this useful.

If there's a reason this interferes with something, please _do_ let me know, but extra unrelated entries /etc/hosts shouldn't hurt anyone :)

I'm going to close this for now, but if it *still* bugs you and you have a sane patch to make this optional, then I'd be happy to merge it.
